collection.c, db.c
https://jira.mongodb.org/browse/PHP-1360
=> PHP-1360: php_mongocursor_is_valid() does not return success/failure constants

collection.c, command_cursor.c, command_cursor.h, cursor.c, cursor_shared.c, cursor_shared.h, db.c, log_stream.c, tests/generic/bug01355.phpt, tests/generic/bug01357.phpt
* https://jira.mongodb.org/browse/PHP-1355
* https://jira.mongodb.org/browse/PHP-1357
=> PHP-1355 and PHP-1357: Fix collection and index enumeration for empty first batch

tests/generic/bug01357.phpt
https://jira.mongodb.org/browse/PHP-1357
----
While 2.8.0-RC3 does support the cursor option for listCollections, it does not respect batchSize and returns all results in a single firstBatch field. RC4 adds full support for batchSize, which makes it possible to test for getmore.
=> PHP-1357: Test case should require server >= 2.8.0-RC4

command_cursor.c, tests/generic/bug01358.phpt, tests/generic/mongocollection-aggregatecursor_error-001.phpt
https://jira.mongodb.org/browse/PHP-1358
=> PHP-1358: Allow command cursor option to be array or object

collection.c, command_cursor.c, command_cursor.h, db.c, tests/generic/bug01358.phpt, tests/generic/mongocollection-aggregatecursor-004.phpt, tests/generic/mongocollection-aggregatecursor-005.phpt, tests/generic/mongocollection-aggregatecursor-006.phpt, tests/generic/mongocollection-aggregatecursor-007.phpt
https://jira.mongodb.org/browse/PHP-1365
----
The driver should not enforce the cursor.batchSize command option, as the server will already use its own default. We should validate that the cursor option is an array/object, and empty arrays should be converted to an object to ensure proper BSON serialization (the server requires an object type).
Only aggregateCursor() requires that we inject the cursor option if it is missing. Collection and index enumeration commands do not require the option at all, as they will always return cursors in 2.8.0-RC4+ and return inline results in earlier versions. RC3 can return an emulated cursor response with only a first batch, but it is practically equivalent to the result when the cursor option is not specified at all.
=> PHP-1365: Validate cursor command option, but don't enforce batchSize

db.c
https://jira.mongodb.org/browse/PHP-1361
----
php_mongo_handle_error() tries to inspect the first result document for an $err field, which is impossible if we never load it first. This makes php_mongo_runcommand() consistent with php_mongo_collection_findone().
=> PHP-1361: Load command result document before php_mongo_handle_error()

tests/no-servers/bug00270-arginfo.phpt
See: fabe53582ad221bd8d8354a60c43928202810bb6
=> PHP-1370: Fix arginfo test after re-ordering method declarations

io_stream.c, tests/generic/bug01247.phpt
https://jira.mongodb.org/browse/PHP-1247
----
This ensures that the stream read handler always enforces the expected timeout for the given MongoClient and server options. If a per-operation timeout is not specified, we previously left the stream as-is, which meant it was possible to inherit the timeout applied by another MongoClient (e.g. previous request).
=> PHP-1247: MongoClient should not inherit timeout of persistent connection

tests/mongos/stream-logger-001.phpt
Caught this failure while testing #825 on 2.4.10. It doesn't appear to fail on `v1.5`, so I'm submitting this against `v1.6`.
=> Fix stream logger test for mongos < 2.5.5

collection.c, mcon/parse.c, tests/generic/bug01400.phpt, tests/standalone/mongoclient-connection-options-fsync-2.6.phpt, tests/standalone/mongoclient-connection-options-journal-2.6.phpt, tests/write/mongocollection-insert-001.phpt
https://jira.mongodb.org/browse/PHP-1400
=> Fixed PHP-1400: Default writeConcern not write safe on standalone node

tests/generic/mongocursor-batchsize-008.phpt
https://jira.mongodb.org/browse/PHP-1405
=> PHP-1405: Regression test for batchSize 1 and -1 behavior

contrib/php-ssl.c, contrib/php-ssl.h, io_stream.c
This builds on PHP-1407 and PHP-1406
=> PHP-1410: Add certificate expiration checks

io_stream.c
https://jira.mongodb.org/browse/PHP-1414
Depends on #841.
=> PHP-1414: SSL peer verification should reference stream->context options

collection.c, tests/generic/mongocollection-distinct-001.phpt, tests/generic/mongocollection-distinct_error-001.phpt
* https://jira.mongodb.org/browse/PHP-1427
* https://jira.mongodb.org/browse/PHP-1433
----
An empty query parameter should be omitted from the command document (consistent with other helpers). This will avoid the case where an empty array is serialized as a BSON array and the server complains that a BSON object was not provided.
Additionally, relax ZPP parsing to allow arrays or objects for the query (also consistent with other helpers).
=> PHP-1427 and PHP-1433: distinct() query param handling

io_stream.c, log_stream.c, log_stream.h
This may address [PHP-1442](https://jira.mongodb.org/browse/PHP-1442) and possibly [PHP-1002](https://jira.mongodb.org/browse/PHP-1002) and [PHP-1417](https://jira.mongodb.org/browse/PHP-1417), too.
Server options are limited to the current request, while the stream itself is persistent. The context should only be accessed through the persistent stream.
Hat tip to @bjori for bringing this to light.
=> PHP-1442: Don't use server options for stream IO notification

mcon/parse.c, tests/no-servers/mongoclient-ssl-001.phpt, tests/no-servers/mongoclient-ssl_error-001.phpt
https://jira.mongodb.org/browse/PHP-1445
To be consistent with other boolean options (e.g. fsync, journal), non-truthy strings should be parsed as a false value. With this change, we can remove the error message that ssl must be true/false; however, we'll keep error reporting for the unsupported "prefer" option value.
=> PHP-1445: Allow boolean false for MongoClient ssl option

mcon/parse.c, tests/no-servers/mongoclient-ssl-001.phpt, tests/no-servers/mongoclient-ssl_error-001.phpt
https://jira.mongodb.org/browse/PHP-1446
=> PHP-1446: Log original and parsed values for boolean options

api/write.c, bson.c, bson.h, command_cursor.c, cursor.c, php_mongo.h, tests/generic/mongocursor-dead-001.phpt, tests/generic/mongocursor-dead-002.phpt, tests/no-servers/bson_decode_error-002.phpt, tests/no-servers/bson_decode_error-003.phpt, tests/no-servers/bug00894.phpt, tests/no-servers/bug01426-001.phpt, tests/no-servers/bug01426-002.phpt, tests/no-servers/bug01426.phpt, tests/no-servers/bug01449-001.phpt, tests/no-servers/bug01449-002.phpt, tests/no-servers/bug01450-001.phpt, tests/no-servers/bug01450-002.phpt, tests/no-servers/bug01450-003.phpt, tests/no-servers/bug01453-001.phpt, types/id.c, types/id.h
* https://jira.mongodb.org/browse/PHP-1426
* https://jira.mongodb.org/browse/PHP-1448
* https://jira.mongodb.org/browse/PHP-1449
* https://jira.mongodb.org/browse/PHP-1450
* https://jira.mongodb.org/browse/PHP-1453
=> PHP-1426 et al: bson_to_zval() fixes

tests/generic/bug00667.phpt
The expected value differed in some newer versions of PHP (with updated timezone DBs). Sticking with UTC keeps the test more resilient to such changes, while still allowing us to deal with negative timestamps.
=> Use UTC timezone for testing pre-epoch dates

command_cursor.c, cursor.c, cursor_shared.c, tests/generic/bug01460-001.phpt, tests/generic/bug01460-002.phpt
https://jira.mongodb.org/browse/PHP-1460
----
This PRs includes two related fixes:
* Make cleanup after failed `php_mongo_get_more()` (for both advancing of command and regular cursors) consistent with the more recently refactored code in `MongoCursor::hasNext()`
* Ensure `php_mongocursor_advance()` kills the cursor when it would be advanced beyond its limit. Additionally, we test that iteration with `getNext()` and `hasNext()` performs as expected.
=> PHP-1460: Advancing cursor beyond its limit should kill it

contrib/crypto.c, contrib/crypto.h
https://jira.mongodb.org/browse/PHP-1462
=> Fixed PHP-1462: Don't expose php_hash_copy by marking it static

gridfs/gridfs.c, tests/generic/bug01464.phpt
Additionally, we'll check for an exception after creating the index so that we can return early (instead of attempting to insert the first chunk and inevitably moving to cleanup).
=> PHP-1464: GridFS should not drop dupes when creating index

mcon/mini_bson.c
https://jira.mongodb.org/browse/PHP-1467
=> PHP-1467: Use endian macros in mini_bson.c functions

rebuild.sh
The stdout suppression is something I've adopted for PHPC's rebuild script, as it makes it easier to focus on compile warnings/errors.
Bumping the `-j` option as a matter of course.
=> Bump make parallelism and suppress stdout in rebuild script

gridfs/gridfs.c, tests/generic/bug01505-001.phpt, tests/generic/bug01505-002.phpt, tests/utils/daemon.php
https://jira.mongodb.org/browse/PHP-1505
Please run `fallocate -l 5G /tmp/5gb` to create a file for the regression test.
=> PHP-1505: Use long and size_t for GridFS file lengths

collection.c
This looks like leftover code from when we still supported PHP 5.2.
See: php/php-src@7da75d81e7993e8c0dd56edf2614be4ce69970a4
=> array_init_size() is defined since PHP 5.3.0

bson.c, tests/no-servers/bug01449-001.phpt, tests/no-servers/bug01449-002.phpt
https://jira.mongodb.org/browse/PHP-1501
Per DRIVERS-281, this also adds field name (for the current nesting level) to the message.
=> PHP-1501: Rephrase exception message for unsupported/corrupt BSON type

gridfs/gridfs.c, php_mongo.h
https://jira.mongodb.org/browse/PHP-1483
This also updates some types in `MongoGridFS::storeBytes()` based on previous changes for [PHP-1505](https://jira.mongodb.org/browse/PHP-1505).
=> PHP-1483: Fix big endian compat for mongo.chunk_size INI

collection.c, tests/standalone/bug01085-001.phpt, tests/standalone/bug01085-002.phpt, tests/standalone/mongoclient-connection-options-fsync-2.6.phpt, tests/standalone/mongoclient-connection-options-journal-2.6.phpt
* https://jira.mongodb.org/browse/PHP-1510
* https://jira.mongodb.org/browse/PHP-1511
My mistake for not catching these test failures in #876. Please see full commit messages for an explanation of changes.
While sorting these out, I also noticed an irregularity with `append_getlasterror()` and opened [PHPC-1511](https://jira.mongodb.org/browse/PHP-1511). I don't believe this affects anything, since the function would not have been called if `is_gle_op()` returned false, but the previous logic looked incorrect nevertheless.
**Note**: This was opened against the wrong branch. Will be merged to `v1.6`.
=> PHP-1510: Fix tests for legacy opcode rerouting

config.m4, contrib/php-ssl.c, contrib/php-ssl.h, io_stream.c, php_mongo.c
https://jira.mongodb.org/browse/PHP-1528
This alters `config.m4` so that we only call `PHP_SUBST(MONGO_SHARED_LIBADD)` once at the end of configuration (after SSL and SASL may have been configured).
=> PHP-1528: Ensure libraries are linked when building with SSL

config.w32
https://jira.mongodb.org/browse/PHP-1528
=> PHP-1528: Ensure HAVE_MONGO_OPENSSL is defined on Windows

contrib/php-ssl.c, contrib/php-ssl.h, io_stream.c
https://jira.mongodb.org/browse/PHP-1529
Supersedes https://github.com/mongodb/mongo-php-driver-legacy/pull/883
=> PHP-1529: Fix undefined symbols from contrib/php-ssl.c
